spring:
  application:
    name: Imooc-Passbook
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbook?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  kafka:
    bootstrap-servers: 192.168.203.165:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  data:
    hbase:
      quorum: 192.168.203.165:2181
      rootDir: hdfs://test165:9000/hbase
      nodeParent: /hbase
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 9528

logging:
  file: ./log/passbook.log
  level:
    root: info
